# dataset path and num class

miniImageNet:
  data_path: "data/cdfsl/mini-ImageNet"
  num_class: 100
  num_data: 60000

miniImageNettest:
  data_path: "data/cdfsl/mini-ImageNet"
  num_class: 100
  num_data: 60000

tieredImageNet:
  data_path: "data/cdfsl/tieredImageNet/train"
  num_class: 351

tieredImageNettest:
  data_path: "data/cdfsl/tieredImageNet/test"
  num_class: 351


ImageNet:
  data_path: "data/cdfsl/ImageNet/train"
  num_class: 1000


# Agriculture
CropDisease:
  data_path: "data/cdfsl/CropDiseases"
  num_class: 38
  num_data: 54305
  split: 43456,10849

# fine-grained classification: original
#CUB:
#  data_path: "data/cdfsl/CUB_200_2011"
#  num_class: 200
#  num_data: 6032
#  split: 3000,3033

# Satellite
EuroSAT:
  data_path: "data/cdfsl/EuroSAT"
  num_class: 10
  num_data: 27000

# Medical
ChestX:
  data_path: "data/cdfsl/chestX"
  num_class: 7
  num_data: 25848

ISIC:
  data_path: "data/cdfsl/ISIC"
  num_class: 7
  num_data: 10015

cars:
  data_path: "data/cdfsl/cars_cdfsl"
  num_class: 196
  num_data: 16185

cub:
  data_path: "data/cdfsl/CUB_200_2011/images"
  num_class: 200
  num_data: 11788

places:
  data_path: "data/cdfsl/places_cdfsl"
  num_class: 16
  num_data: 27440

plantae:
  data_path: "data/cdfsl/plantae_cdfsl"
  num_class: 69
  num_data: 26650
